name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number"
        required: true
      createTag:
        description: "Create a new release"
        type: boolean
        required: false
        default: false
      prerelease:
        description: "Is prerelease ?"
        type: boolean
        required: false
        default: false
      draft:
        description: "Is draft ?"
        type: boolean
        required: false
        default: false

jobs:
  bumpVersion:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install xmlstarlet
        run: sudo apt install -y xmlstarlet

      - name: Install Maven
        run: sudo apt install maven

      - name: Bump version in POM files
        run: mvn versions:set -DnewVersion=${{ github.event.inputs.version }} -q

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.ACTOR_TOKEN }}
          author_email: ${{ secrets.ACTOR_EMAIL }}
          author_name: ${{ secrets.ACTOR_NAME }}
          message: 'build: bump version to ${{ github.event.inputs.version }}'

      - name: Create Release
        if: ${{ github.event.inputs.createTag == 'true' }}
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          generateReleaseNotes: true
          tag: ${{ github.event.inputs.version }}
          name: Release v${{ github.event.inputs.version }}
          draft: ${{ github.event.inputs.draft }}
          prerelease: ${{ github.event.inputs.prerelease }}
          makeLatest: ${{ github.event.inputs.prerelease == 'false' }}
