name: Verify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checkstyle:
    name: Verify Code Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dbelyaev/action-checkstyle@v0.7.4
        with:
          reporter: github-pr-review

  conventional-commits:
    name: Verify Commit Messages
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: webiny/action-conventional-commits@v1.2.0

  dependency-review:
    name: Verify Dependencies
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          comment-summary-in-pr: always
          fail-on-severity: moderate

  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract-version.outputs.version }}
      version-without-suffix: ${{ steps.extract-version.outputs.version-without-suffix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install xmlstarlet
        run: sudo apt update && sudo apt install -y xmlstarlet

      - name: Extract Project Version
        id: extract-version
        run: |
          version=$(xmlstarlet sel -N pom="http://maven.apache.org/POM/4.0.0" \
            -t -v "/pom:project/pom:version" \
            pom.xml)
          version_without_suffix="${version%-SNAPSHOT}"
          echo "::set-output name=version::$version"
          echo "::set-output name=version-without-suffix::$version_without_suffix"
  tests:
    needs: setup
    runs-on: ubuntu-latest
    container: "webforj/sandbox:${{ needs.setup.outputs.version-without-suffix }}"
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Install Maven
        run: apk add maven

      - name: Install Maven Dependencies
        run: >
          mvn install:install-file "-Dfile=/opt/bbx/.lib/BBjStartup.jar" "-DgroupId=com.basis.lib" "-DartifactId=BBjStartup" "-Dversion=${{ needs.setup.outputs.version }}" "-Dpackaging=jar" -q
          && mvn install:install-file "-Dfile=/opt/bbx/.lib/BBj.jar" "-DgroupId=com.basis.lib" "-DartifactId=BBj" "-Dversion=${{ needs.setup.outputs.version }}" "-Dpackaging=jar" -q
          && mvn install:install-file "-Dfile=/opt/bbx/.lib/BBjUtil.jar" "-DgroupId=com.basis.lib" "-DartifactId=BBjUtil" "-Dversion=${{ needs.setup.outputs.version }}" "-Dpackaging=jar" -q
          && mvn install:install-file "-Dfile=/opt/bbx/.lib/BBjsp.jar" "-DgroupId=com.basis.lib" "-DartifactId=BBjsp" "-Dversion=${{ needs.setup.outputs.version }}" "-Dpackaging=jar" -q
          && mvn install:install-file "-Dfile=/opt/bbx/.lib/BBjAdminAPI.jar" "-DgroupId=com.basis.lib" "-DartifactId=BBjAdminAPI" "-Dversion=${{ needs.setup.outputs.version }}" "-Dpackaging=jar" -q
          && mvn install -q -DskipTests

      - name: Build with Maven
        run: mvn -B verify

      - name: Jacoco Report
        # if: github.event_name == 'pull_request'
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/webforj-report-aggregate/target/site/jacoco-aggregate/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
          title: Code Coverage
          update-comment: true

      - name: Get the Coverage info
        run: |
          echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
          echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"
