name: Version

on:
  repository_dispatch:
    types: [version]
  workflow_dispatch:
    inputs:
      version:
        description: "Version number"
        required: true
      createRelease:
        description: "Create a new release"
        type: boolean
        required: false
        default: false

env:
  VERSION: ${{ github.event.client_payload.version || github.event.inputs.version }}
  CREATE_RELEASE: ${{ github.event.client_payload.createRelease || github.event.inputs.createRelease }}

jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set version with SNAPSHOT if not creating a release
        id: set_version
        run: |
          if [ "${{ env.CREATE_RELEASE }}" != "true" ]; then
            echo "VERSION=${{ env.VERSION }}-SNAPSHOT" >> $GITHUB_ENV
          else
            echo "VERSION=${{ env.VERSION }}" >> $GITHUB_ENV
          fi

      - name: Install Maven
        run: sudo apt install maven

      - name: Bump version in POM files
        run: mvn versions:set -DnewVersion=${{ env.VERSION }} -q

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.ACTOR_TOKEN }}
          author_email: ${{ secrets.ACTOR_EMAIL }}
          author_name: ${{ secrets.ACTOR_NAME }}
          message: 'build: bump version to ${{ env.VERSION }}'

      - name: Create Release
        if: ${{ env.CREATE_RELEASE == 'true' }}
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          generateReleaseNotes: true
          tag: ${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          makeLatest: true
